FROM buildo/scala-sbt-alpine:8u201_2.12.11_1.3.9 as build

WORKDIR /srv/api

ADD project project
ADD build.sbt .
RUN sbt update

ADD . .
RUN sbt assembly

FROM openjdk:8-jre-alpine

EXPOSE 8080

COPY --from=build /srv/api/target/scala-2.12/root.jar /srv/api.jar

ADD wait-for /usr/bin/

CMD /usr/bin/java -cp /srv/api.jar trovamascherine.NotificationBoot
