FROM buildo/scala-sbt-alpine:8u201_2.12.11_1.3.9 as build

WORKDIR /srv/api

ADD project project
ADD build.sbt .
RUN sbt update

ADD . .
RUN sbt fixtures/assembly

FROM openjdk:8-jre-alpine

COPY --from=build /srv/api/fixtures/target/scala-2.12/fixtures.jar /srv/fixtures.jar

ADD wait-for /usr/bin/

CMD /usr/bin/java -cp /srv/fixtures.jar trovamascherine.fixtures.Boot
